dist: trusty
language: c

cache:
  directories:
  - $HOME/.opam

env:
  global:
  - OPAMJOBS="2"
  - OPAMYES="true"
  - OPAMVERBOSE="true"
  matrix:
  - OCAML_VERSION=4.03.0
  - OCAML_VERSION=4.04.0
  - OCAML_VERSION=4.04.1
  - OCAML_VERSION=4.04.2
  - OCAML_VERSION=4.05.0
  - OCAML_VERSION=4.06.1
  - OCAML_VERSION=4.07.1
  - OCAML_VERSION=4.08.1
  - OCAML_VERSION=4.09.0

before_install:
  # Install lablgl dependencies
  - sudo apt-get install -y freeglut3-dev libglu1-mesa-dev mesa-common-dev
  # Obtain and install opam locally.
  - sudo wget https://github.com/ocaml/opam/releases/download/2.0.5/opam-2.0.5-x86_64-linux -O /usr/bin/opam
  - sudo chmod 755 /usr/bin/opam
  # Initialize the switch.
  - opam init -a --disable-sandboxing --compiler="$OCAML_VERSION"
  - opam update
  - opam switch "$OCAML_VERSION"
  - eval $(opam env)
  # Install deps
  - opam install dune earley.2.0.0 camlzip imagelib sqlite3 cairo2 cryptokit lablgl

install:
  - make
  - make install

script:
  - cd patobook
  - make
  - echo "OK"

notifications:
  email:
    - rodolphe.lepigre@inria.fr
