let prefix=ref "/usr/local/"
let bin_dir=ref ""
let fonts_dir=ref ""
let grammars_dir=ref ""
let hyphen_dir=ref ""
let ocaml_lib_dir=ref ""
let ocamlfind_dir=ref ""
let fonts_dirs=ref []
let grammars_dirs=ref []
let hyphen_dirs=ref []
let camlzip=ref ""
let camlimages=ref ""
let lang=ref "FR"
let ban_comic_sans=ref false


let avail_lang=
  let f=open_in "src/Typography/Language.ml" in
  let buf=String.create (in_channel_length f) in
    really_input f buf 0 (in_channel_length f);
    close_in f;
    let rec make_str i res=
      if i>String.length buf-7 then res else
        make_str (i+1)
          (if String.sub buf i 5="LANG_" then
             String.sub buf (i+5) 2::res
           else res)
    in
      make_str 0 []

open Arg
let rec escape s=
  try
    let i=String.index s ' ' in
      String.sub s 0 i ^ "\\ " ^ (escape (String.sub s (i+1) (String.length s-i-1)))
  with
      Not_found -> s

let is_substring s1 s0=
  let rec sub i j=
    if i>String.length s0-String.length s1 then false else
      if j>=String.length s1 then true else
        if s0.[i+j]=s1.[j] then sub i (j+1) else
          sub (i+1) 0
  in
    sub 0 0

let _=
  parse [
    ("--prefix", Set_string prefix, "  prefix (/usr/local/ by default)");
    ("--bin-prefix", Set_string bin_dir, "  directory for the binaries ($PREFIX/bin/ by default)");
    ("--ocaml-libs", Set_string ocaml_lib_dir, "  directory for the caml libraries ($PREFIX/lib/ocaml/ by default; `ocamlc -where` is another sensible choice)");
    ("--ocamlfind-dir", Set_string ocamlfind_dir, "  directory for the caml libraries ($PREFIX/lib/ocaml/ by default; `ocamlc -where` is another sensible choice)");
    ("--fonts-dir", Set_string fonts_dir, "  directory for the fonts ($PREFIX/share/patoline/fonts/ by default)");
    ("--grammars-dir", Set_string grammars_dir, "  directory for the grammars ($PREFIX/lib/patoline/grammars/ by default)");
    ("--hyphen-dir", Set_string hyphen_dir, "  directory for the hyphenation dictionnaries ($PREFIX/share/patoline/hyphen/ by default)");
    ("--extra-fonts-dir", String (fun pref->fonts_dirs:=pref:: !fonts_dirs), "  additional directories patoline should scan for fonts");
    ("--extra-grammars-dir", String (fun pref->grammars_dirs:=pref:: !grammars_dirs), "  additional directories patoline should scan for grammars");
    ("--extra-hyphen-dir", String (fun pref->hyphen_dirs:=pref:: !hyphen_dirs), "  additional directories patoline should scan for hyphenation dictionaries");
    ("--ban-comic-sans", Set ban_comic_sans, " disallows the use of a font with name '*comic*sans*'. Robust to filename changes.");
    ("--lang", Set_string lang, Printf.sprintf "  language of the error messages (english by default), available : %s"
       (String.concat ", " (List.rev avail_lang)))
  ] ignore "Usage:";
  if !bin_dir="" then bin_dir:=Filename.concat !prefix "bin/";
  if !ocaml_lib_dir="" then ocaml_lib_dir:=Filename.concat !prefix "lib/ocaml";
  if !fonts_dir="" then fonts_dir:=Filename.concat !prefix "share/patoline/fonts";
  if !grammars_dir="" then grammars_dir:=Filename.concat !prefix "lib/patoline/grammars";
  if !hyphen_dir="" then hyphen_dir:=Filename.concat !prefix "share/patoline/hyphen";

  fonts_dirs:= !fonts_dir ::(!fonts_dirs);
  grammars_dirs:= !grammars_dir ::(!grammars_dirs);
  hyphen_dirs:= !hyphen_dir ::(!hyphen_dirs);

  if Sys.command "ocamlfind query zip" = 0
  then camlzip := "zip"
  else if Sys.command "ocamlfind query camlzip" = 0
  then camlzip := "camlzip";

  if Sys.command "ocamlfind query camlimages" = 0
  then camlimages := "camlimages.all_formats";

  let out=open_out "Makefile" in
  let config=open_out "src/Typography/Config.ml" in
  let config'=open_out "src/Patoline/PatolineConfig.ml" in

  let fonts_src_dir="Fonts" in
  let grammars_src_dir="src/_build" in
  let hyphen_src_dir="Hyphenation" in
  let emacsdir = Filename.concat !prefix "share/emacs/site-lisp/patoline" in

  let tests = ["min.txp";"TD1.txp"] in

    Printf.fprintf out "# DO NOT EDIT THIS FILE\n";
    Printf.fprintf out "# generated by 'ocaml configure.ml'\n\n";
    Printf.fprintf out "all:\n\tmake -C src all\n\tmake emacs\n";
    Printf.fprintf out "binary:all\nbuild:all\n";
    Printf.fprintf out "doc: Patoline.pdf\n\n";
    Printf.fprintf out "Patoline.pdf: Patoline.txp\n\tmake -C src doc\n\t./src/_build/Patoline/Main.native --extra-fonts-dir ../Fonts -I src/_build Patoline.txp\n";
    Printf.fprintf out "check: doc\n";
    List.iter (fun txp ->
      Printf.fprintf out "\tcd tests; ../src/_build/Patoline/Main.native -I ../src --extra-fonts-dir ../Fonts --format FormatArticle %s\n" txp) tests;

    Printf.fprintf out ".PHONY: emacs\nemacs:\n\tcd emacs; cat patoline-input.pre ../src/_build/quail.el patoline-input.post > patoline-input.el\n";

    Printf.fprintf out "install:\n";
    Printf.fprintf out "\t#fonts\n";
    let rec read_fonts dir =
      Printf.fprintf out "\tinstall -m 755 -d $(DESTDIR)%s\n" (escape (Filename.concat !fonts_dir dir));
      List.iter (fun f->
        let f = Filename.concat dir f in
        if Sys.is_directory f
        then read_fonts f
        else if Filename.check_suffix f ".otf" then
          Printf.fprintf out "\tinstall -m 644 %s $(DESTDIR)%s\n"
            (escape (Filename.concat fonts_src_dir f))
            (escape (Filename.concat !fonts_dir f))
            ) (Array.to_list (Sys.readdir dir))
    in
    let cdir = Sys.getcwd () in
      Sys.chdir fonts_src_dir;
      read_fonts "./";
      Sys.chdir cdir;

    (* Grammars *)
    Printf.fprintf out "\t#grammars\n";
    Printf.fprintf out "\tinstall -m 755 -d $(DESTDIR)%s\n" (escape !grammars_dir);
    Printf.fprintf out "\tinstall -m 644 %s $(DESTDIR)%s\n" 
      (escape (Filename.concat grammars_src_dir "DefaultGrammar.tgx")) 
      (escape (List.hd !grammars_dirs));

    (* Hyphenation *)
    Printf.fprintf out "\t#hyphenation\n";
    Printf.fprintf out "\tinstall -m 755 -d $(DESTDIR)%s\n" (escape !hyphen_dir);
    List.iter (fun x->
                 if Filename.check_suffix x ".hdict" then
                   Printf.fprintf out "\tinstall -m 644 %s $(DESTDIR)%s\n" (escape (Filename.concat hyphen_src_dir x)) (escape !hyphen_dir)
              ) (Array.to_list (Sys.readdir hyphen_src_dir));

    let tags=open_out "src/Typography/_tags" in
      Printf.fprintf tags
        "<**/*.ml> or <**/*.mli>: package(camomile)%s%s,pp(cpp -w %s%s%s%s)
<**/*.{cmo,cmx}> and not <Typography.*>:for-pack(Typography)
<Fonts> or <Output> or <Output/Drivers>:include\n"
        (if !camlzip <> "" then ",package("^(!camlzip)^")" else "")
        (if !camlimages <> "" then ",package("^(!camlimages)^")" else "")
        (if !camlzip <> "" then "-DCAMLZIP " else "")
        (if !camlimages <> "" then "-DCAMLIMAGES " else "")
        (if !ban_comic_sans then "-DBAN_COMIC_SANS " else "")
        (if String.uppercase !lang <> "EN" then ("-DLANG_"^String.uppercase !lang) else "");
      close_out tags;

    let tags=open_out "src/_tags" in
      Printf.fprintf tags
        "<**/*>: pp(cpp -w),package(camomile)%s%s
<Format/*.{ml,mli}>: use_Typography,use_str
<proof/proof.{byte,native}>: package(camomile)%s%s
<Patoline/*>:pp(cpp -w %s),package(dyp),use_str,rectypes
<Typography/Break.ml>:rectypes
\"Typography\":include\n"
        (if !camlzip <> "" then ",package("^(!camlzip)^")" else "")
        (if !camlimages <> "" then ",package("^(!camlimages)^")" else "")
        (if !camlzip <> "" then ",package("^(!camlzip)^")" else "")
        (if !camlimages <> "" then ",package("^(!camlimages)^")" else "")
        (if String.uppercase !lang <> "EN" then ("-DLANG_"^String.uppercase !lang) else "");

      close_out tags;

    (* binaries *)
    Printf.fprintf out "\t#binaries\n";
    Printf.fprintf out "\tinstall -d $(DESTDIR)%s\n" (escape !bin_dir);
    Printf.fprintf out "\tinstall -m 755 src/_build/Patoline/Main.native $(DESTDIR)%s/patoline\n" (escape !bin_dir);

    let sources=
      "src/_build/Typography/Typography.cmxa src/_build/Typography/Typography.p.cmxa src/_build/Typography/Typography.a src/_build/Typography/Typography.p.a src/_build/Typography/Typography.cmi "^
        "src/_build/Format/*Format*.cmxa src/_build/Format/*Format*.a src/_build/Format/*Format*.cmi "^
        "src/_build/Typography/Typography.cma src/_build/Format/*Format*.cma"
    in
      Printf.fprintf out "\tinstall -m 755 -d $(DESTDIR)%s/Typography\n" (escape !ocaml_lib_dir);
      Printf.fprintf out "\tinstall -m 644 %s $(DESTDIR)%s/Typography\n" sources (escape !ocaml_lib_dir);

      Printf.fprintf out "\tinstall -m 755 -d $(DESTDIR)%s/Typography\n" (escape !ocaml_lib_dir);


      Printf.fprintf out "\tinstall -m 755 -d $(DESTDIR)%s/Typography\n" (if !ocamlfind_dir="" then "$(shell ocamlfind printconf destdir)" else escape !ocamlfind_dir);
      Printf.fprintf out "\tinstall -m 644 src/Typography/META %s $(DESTDIR)%s/Typography\n" sources (if !ocamlfind_dir="" then "$(shell ocamlfind printconf destdir)" else escape !ocamlfind_dir);

      (* proof *)
      Printf.fprintf out "\tinstall -m 755 src/_build/proof/proof.native $(DESTDIR)%s/proof\n" (escape !bin_dir);

      (* emacs *)
      Printf.fprintf out "\tcd emacs; install -m 755 -d $(DESTDIR)%s\n" emacsdir;
      Printf.fprintf out "\tcd emacs; install -m 644 *.el $(DESTDIR)%s/\n" emacsdir;

      (* Ecriture de la configuration *)
      let conf=if Sys.os_type= "Win32" then (
        let path_var="PATOLINE_PATH" in
          Printf.sprintf "(** Configuration locale (chemins de recherche des fichiers) *)\nlet path=try Sys.getenv %S with _->\"\"\n(** Chemin des polices de caractères *)\nlet fontsdir=ref [%s]\n(** Chemin de l'éxécutable Patoline *)\nlet bindir=%S\n(** Chemin des grammaires *)\nlet grammarsdir=ref [%s]\n(** Chemin des dictionnaires de césures *)\nlet hyphendir=ref [%s]\n"
            path_var
            (String.concat ";" ("\".\""::List.map (Printf.sprintf "Filename.concat path %S") (List.rev !fonts_dirs)))
            !bin_dir
            (String.concat ";" ("\".\""::List.map (Printf.sprintf "Filename.concat path %S") (List.rev !grammars_dirs)))
            (String.concat ";" ("\".\""::List.map (Printf.sprintf "Filename.concat path %S") (List.rev !hyphen_dirs)))
      ) else (
        Printf.sprintf "(** Configuration locale (chemins de recherche des fichiers) *)\n(** Chemin des polices de caractères *)\nlet fontsdir=ref [%s]\n(** Chemin de l'éxécutable Patoline *)\nlet bindir=%S\n(** Chemin des grammaires *)\nlet grammarsdir=ref [%s]\n(** Chemin des dictionnaires de césures *)\nlet hyphendir=ref [%s]\nlet local_path:string list ref=ref []\n"
          (String.concat ";" (List.map (Printf.sprintf "%S") (List.rev !fonts_dirs)))
          !bin_dir
          (String.concat ";" (List.map (Printf.sprintf "%S") (List.rev !grammars_dirs)))
          (String.concat ";" (List.map (Printf.sprintf "%S") (List.rev !hyphen_dirs)))
      )
      in
        Printf.fprintf config "%s" conf;
        Printf.fprintf config' "%s" conf;
        Printf.fprintf out "clean:\n\tmake -C src clean\n";
        Printf.fprintf out "distclean: clean\n\trm -f Makefile src/Typography/Config.ml src/Patoline/PatolineConfig.ml src/Typography/_tags src/_tags src/Typography/META\n";
        close_out out;
        close_out config;
        close_out config';

        let meta=open_out "src/Typography/META" in
          Printf.fprintf meta
            "name=\"Typography\"\nversion=\"1.0\"\ndescription=\"Typography library\"\nrequires=\"str,camomile%s%s\"\n" (if !camlzip="" then "" else (","^(!camlzip)))
            (if !camlimages="" then "" else (","^(!camlimages)));
          Printf.fprintf meta "archive(native)=\"Typography.cmxa, DefaultFormat.cmxa\"\n";
          Printf.fprintf meta "archive(byte)=\"Typography.cma, DefaultFormat.cma\"\n";
          Array.iter (fun x->
                        if Filename.check_suffix x ".ml" && is_substring "Format" x
                          && x<>"DefaultFormat.ml"
                        then (
                          let base_x = Filename.chop_extension x in
                          Printf.fprintf meta "package \"%s\" (\n" base_x;
                          Printf.fprintf meta "requires=\"Typography\"\n";
                          Printf.fprintf meta "archive(native)=\"%s\"\n"
                            (base_x^".cmxa");
                          Printf.fprintf meta "archive(byte)=\"%s\"\n"
                            (base_x^".cma");
                          let custom_meta = Filename.concat "src/Format/" (base_x^".META") in
                          (try
                            let custom_meta_fd = open_in custom_meta in
                            let buf = String.create (in_channel_length custom_meta_fd) in
                            really_input custom_meta_fd buf 0 (in_channel_length custom_meta_fd);
                            close_in custom_meta_fd;
                            Printf.fprintf meta "%s\n" buf
                          with Sys_error _ -> ());
                          Printf.fprintf meta ")\n";
                        )
                     ) (Sys.readdir "src/Format");
          close_out meta;
          Printf.printf "\nConfigure finished\n
You can now build by doing:
	make
	make install

And optionally
	make doc
	make check

"
