pdf_parser.cmxa:
	ocamlbuild -classic-display pdf_parser.cmxa

pdf_parser.p.cmxa:
	ocamlbuild -classic-display  pdf_parser.p.cmxa

pdf_parser.cma:
	ocamlbuild -classic-display  pdf_parser.cma

clean:
	rm -Rf *~ _build
