(* This file reads src/Typography/META from the source tree to extract the first
 * lines about Typography itself (without drivers or formats), and builds the
 * postinst script for libtypography-ocaml-dev which generates the full META for
 * Typography and all installed drivers and formats.
 *
 * We expect this script to be called with "src/Typography/META" as its standard
 * input.
 *
 * The content of libtypography-ocaml-dev.postinst is printed on stdout.
 *)

let _ = print_endline "#!/bin/sh -e

printf \"Updating Typography package list...\"

libdir=/usr/lib/ocaml/Typography/
destmeta=$libdir/META

cat > $destmeta <<EOF
# DO NOT EDIT THIS FILE -- YOUR CHANGES WILL BE OVERWRITTEN
# This file is generated by libtypography-ocaml-dev postinstall
# script/trigger." ;

(try
  let package_re = Str.regexp "^package" in
  let rec meta_line () =
    let l = read_line () in
    if not (Str.string_match package_re l 0)
    then (print_endline l; meta_line ())
  in meta_line ()
with _ -> ());

print_endline "EOF

for file in $libdir/*.cmxa
do
  basefile=`basename $file .cmxa`
  if [ $basefile != \"Typography\" ]
  then
    if [ -r $libdir/META.d/$basefile.META ]
    then
      cat $libdir/META.d/$basefile.META >> $destmeta
    else
      echo \"package \\\"$basefile\\\" (\" >> $destmeta
      echo \"archive(byte)=\\\"$basefile.cma\\\"\" >> $destmeta
  
      if [ -r \"$libdir/$basefile.cmxa\" ]
      then
        echo \"archive(native)=\\\"$basefile.cmxa\\\"\" >> $destmeta
      fi
  
      echo \")\" >> $destmeta
    fi
  fi
done

printf \" done.\n\"

#DEBHELPER#"

