#!/usr/bin/python
import sys
import os

uri = sys.argv[1].replace("%20"," ")

[protocol, location] = uri.split(":")

# log = open("/tmp/xpdflog", mode='a')
# log.write(uri+"\n")
# log.close()

if (protocol == "edit"):
    [filename, linenum, colnum] = location.split("@")
    os.execlp("emacsclient", "-n", "--eval",
              '(patoline-goto "' + filename +'" ' + str(linenum) + ' ' + str(colnum) + ")")
else:
    os.execlp("firefox", "uri")
          

